### PR TITLE
Aeroo V9 fixes

### PR DESCRIPTION
**Pull request by Yenthe666**
These changes make Aeroo fully compatible with Odoo 9.

### CODE REVIEW

**Comment by Yenthe666** [comment]
@sraps,

This is the fully working Aeroo module for Odoo V9. I'd suggest you to create a 9.0 branch where you pull this in to? Master can be the development branch then.

**Comment by parthivgls** [comment]
I have tried your branch, it works and give output in ODS but when I tried to convert it to PDF or DOC, it fails. also the connection check is endless.

**Comment by Yenthe666** [comment]
@parthivgls have a look at this thread: https://github.com/aeroo/aeroo_reports/pull/71
Odoo has to port a fix from 8.0 to V9, as seen here: https://github.com/odoo/odoo/pull/10080
As for the endless connection: this means you either setup the connection incorrectly or didn't reboot your system before trying to connect (which is required)

**Comment by lukebranch** [comment]
@parthivgls ,

Did you happen to have this error during the setup process?:

```
Downloading/unpacking jsonrpc2
  Downloading jsonrpc2-0.4.1-py2.py3-none-any.whl
Downloading/unpacking daemonize
  Downloading daemonize-2.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from jsonrpc2)
Installing collected packages: jsonrpc2, daemonize
*** Error compiling '/tmp/pip_build_root/jsonrpc2/jsonrpc2/cmd.py'...
  File "/tmp/pip_build_root/jsonrpc2/jsonrpc2/cmd.py", line 15
    print 'runserver %s:%d' % (host, port)
                          ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip_build_root/jsonrpc2/jsonrpc2/gae.py'...
  File "/tmp/pip_build_root/jsonrpc2/jsonrpc2/gae.py", line 49
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Successfully installed jsonrpc2 daemonize
Cleaning up...
```

and what specifications are your dev server?

**Comment by parthivgls** [comment]
No, I haven't got that error. Just that server is listing for permanently.
I am waiting for that search merge to be completed for doing further
testing.

On Mon, Dec 28, 2015 at 5:07 PM, Luke Branch notifications@github.com
wrote:

> @parthivgls https://github.com/parthivgls ,
> 
> Did you happen to have this error during the setup process?:
> 
> Downloading/unpacking jsonrpc2
>   Downloading jsonrpc2-0.4.1-py2.py3-none-any.whl
> Downloading/unpacking daemonize
>   Downloading daemonize-2.4.2-py2.py3-none-any.whl
> Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from jsonrpc2)
> Installing collected packages: jsonrpc2, daemonize
> **\* Error compiling '/tmp/pip_build_root/jsonrpc2/jsonrpc2/cmd.py'...
>   File "/tmp/pip_build_root/jsonrpc2/jsonrpc2/cmd.py", line 15
>     print 'runserver %s:%d' % (host, port)
>                           ^
> SyntaxError: invalid syntax
> 
> **\* Error compiling '/tmp/pip_build_root/jsonrpc2/jsonrpc2/gae.py'...
>   File "/tmp/pip_build_root/jsonrpc2/jsonrpc2/gae.py", line 49
>     except ValueError, e:
>                      ^
> SyntaxError: invalid syntax
> 
> Successfully installed jsonrpc2 daemonize
> Cleaning up...
> 
> and what specifications are your dev server?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aeroo/aeroo_reports/pull/72#issuecomment-167549874.

## 

Thanks & Regards,
Parthiv Patel

**Comment by lukebranch** [comment]
@parthivgls ,

I was having some similar issues to you in newer installations of Odoo + Aeroo and I believe it may have to do with the format of:

/etc/init.d/office

and the search merge I mentioned previously.

Try changing the contents of:

/etc/init.d/office

to match:

https://github.com/luca-vercelli/aeroo_docs/blob/cfc1b536c630c98a1c6447df21059997028b00c0/debian/office

and make the change in the merge mentioned in main.py locally on your dev machine.

Once I did this and upgraded base (ie. the base module) and then rebooted the machine I had no more issues with Aeroo not finding Aeroo-Docs.

I'll try and reproduce this on a clean VM again tomorrow and then pass the changes on to Yenthe for him to merge into his fork of the Aeroo install script.

**Comment by Yenthe666** [comment]
@sraps could this please be merged in? It is so annoying that I have to manually update my module after cloning from here. I'd like version 9.0 to be available here and on the Odoo apps store :+1:

**Comment by lmignon** [comment]
@Yenthe666 I try to use your branch on a fresh V9 but in my case, the sample parser doesn't work since to used parser is not the one defined on the sample report. Do you have tried the sample report?

**Comment by Yenthe666** [comment]
@lmignon I didn't need the report parsing systems really so I haven't tested the sample reports.
My branch works fine for me when I install a clean Odoo 9 with a Aeroo server connection configured. I can create a new Aeroo report and it will work fine.

**Comment by lmignon** [comment]
@Yenthe666 Thank you for the quick response. I've just found my prob. It comes from the way custom parser classes are loaded (https://github.com/aeroo/aeroo_reports/blob/master/report_aeroo/report_xml.py#L105). This way of loading parser class is not compatible with addons packaged with pip and server started withhttps://github.com/acsone/odoo-autodiscover  PR #81. By the way the proposed change simplify the code.

**Comment by Yenthe666** [comment]
@lmignon does the pull request you proposed work with both the PIP and without the pip installation?
If this is the case please also propose it against my V9 version, I'll merge it in there. It seems that the official Aeroo repository is really dead..

**Comment by lmignon** [comment]
Yes it works with both

**Pull request closed without merging**
